service: lambda-edge-ts
# frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  memorySize: 1024 # repository wide Lambda memory size
  stage: production
  timeout: 30 # repository wide Lambda timeout
  environment: # repository wide Lambda env variables
    NODE_ENV: production
    VERSION: v20.0

plugins:
  - serverless-offline # used for local execution

custom:
  serverless-offline:
    httpPort: 5000

functions:
  server:
    handler: ./src/index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      # - http:
      #     path: /{proxy+}
      #     method: ANY
      #     cors: true
