service: lambda-edge-ts

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  memorySize: 1024
  stage: production
  timeout: 300
  environment:
    NODE_ENV: production
    VERSION: v20.0

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 5000

functions:
  server:
    handler: ./src/index.handler
    # Local development HTTP event
    events:
      - http:
          path: /
          method: ANY
          cors: true