service: lambda-edge-ts
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  memorySize: 1024 # repository wide Lambda memory size
  stage: dev
  timeout: 30 # repository wide Lambda timeout
  environment: # repository wide Lambda env variables
    NODE_ENV: production
    VERSION: v20.0

plugins:
  - serverless-offline # used for local execution

functions:
  app:
  handler: src/handler.handler
  events:
    - http:
        path: /
        method: any
        cors: true
    - http:
        path: /{proxy+}
        method: any
        cors: true
